const NEW_KEY='vthangSiteDataV8',OLD_KEY='vthangSiteDataV7',GH_KEY='vthangGithubTokenV2';
const GH_OWNER='thandenaov',GH_REPO='thandenaov.github.io',GH_BRANCH='main',GH_PATH='data.json';
const $=s=>document.querySelector(s);let data,adminUnlocked=false;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','"':'&quot;'}[c]));

function migrateOption(o={},fallback='Lựa chọn'){const children=Array.isArray(o.children)?o.children.map((x,i)=>migrateOption(x,`Lựa chọn ${i+1}`)):[];return {label:o.label||fallback,description:o.description||'',hasDescription:o.hasDescription??Boolean(o.description),url:o.url||'',hasChildren:o.hasChildren??Boolean(children.length),children}}
function normalizeProduct(p={}){
  const legacy=(type)=>{const a=Array.isArray(p[type+'Options'])?p[type+'Options']:[];return a.map((x,i)=>migrateOption(x,`Lựa chọn ${i+1}`))};
  p.downloadOptions=legacy('download');p.keyOptions=legacy('key');p.guideOptions=(p.guideOptions||[]).map((x,i)=>migrateOption(x,`Lựa chọn ${i+1}`));
  p.guideType=p.guideType||'text';p.guideText=p.guideText??p.guide??'';p.guideUrl=p.guideUrl||'';p.guideVideo=p.guideVideo||'';
  p.previewImages=Array.isArray(p.previewImages)&&p.previewImages.length?p.previewImages.filter(Boolean):(p.previewImage?[p.previewImage]:p.cover?[p.cover]:[]);
  p.downloadUrl=p.downloadUrl||'';p.keyUrl=p.keyUrl||'';return p;
}
function normalizeData(x={}){x.version=8;x.notifications=Array.isArray(x.notifications)?x.notifications:[];x.socials=Array.isArray(x.socials)?x.socials:[];x.products=(x.products||[]).map(normalizeProduct);x.effects={particles:true,avatarGlow:true,verifiedShine:true,backgroundMotion:true,...(x.effects||{})};return x}
function getPath(path){return path.split('.').reduce((o,k)=>o?.[/^\d+$/.test(k)?Number(k):k],data)}
function setPath(path,value){const parts=path.split('.');let o=data;for(let i=0;i<parts.length-1;i++){const k=/^\d+$/.test(parts[i])?Number(parts[i]):parts[i];if(o[k]==null)o[k]={};o=o[k]}const k=/^\d+$/.test(parts.at(-1))?Number(parts.at(-1)):parts.at(-1);o[k]=value}
function arrayAt(path){const a=getPath(path);return Array.isArray(a)?a:null}

async function unlock(){if(adminUnlocked)return;adminUnlocked=true;$('#loginError').textContent='';$('#loginForm').reset();const gate=$('#loginGate');$('#adminApp').hidden=false;gate.classList.add('is-closing');try{await init()}catch(err){console.error(err);alert('Không tải được dữ liệu quản trị.')}setTimeout(()=>gate.remove(),170)}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#loginPass').value==='minhwuan')unlock();else{$('#loginError').textContent='Sai mật khẩu.';$('#loginPass').select()}});$('#loginPass').addEventListener('input',()=>$('#loginError').textContent='');$('#logoutBtn').onclick=()=>location.reload();

function loadGithubToken(){return localStorage.getItem(GH_KEY)||''}function saveGithubToken(v){localStorage.setItem(GH_KEY,v)}
function githubSettings(){return {owner:GH_OWNER,repo:GH_REPO,branch:GH_BRANCH,path:GH_PATH,token:document.querySelector('[data-gh="token"]')?.value.trim()||''}}
function setGithubStatus(t,type=''){const el=$('#githubStatus');el.textContent=t;el.className='github-status '+type}
function utf8ToBase64(text){const bytes=new TextEncoder().encode(text);let b='';for(let i=0;i<bytes.length;i+=0x8000)b+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(b)}
async function githubRequest(url,token,options={}){const r=await fetch(url,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.message||`GitHub HTTP ${r.status}`);return body}
async function getGithubFile(s){const url=`https://api.github.com/repos/${encodeURIComponent(s.owner)}/${encodeURIComponent(s.repo)}/contents/${s.path.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(s.branch)}`;try{return await githubRequest(url,s.token)}catch(e){if(/404|Not Found/i.test(e.message))return null;throw e}}
async function saveDataToGithub(){const s=githubSettings();if(!s.token)throw new Error('Hãy nhập GitHub Token.');saveGithubToken(s.token);const old=await getGithubFile(s),url=`https://api.github.com/repos/${encodeURIComponent(s.owner)}/${encodeURIComponent(s.repo)}/contents/${s.path.split('/').map(encodeURIComponent).join('/')}`;const payload={message:`Cập nhật website ${new Date().toLocaleString('vi-VN')}`,content:utf8ToBase64(JSON.stringify(data,null,2)),branch:s.branch};if(old?.sha)payload.sha=old.sha;return githubRequest(url,s.token,{method:'PUT',body:JSON.stringify(payload)})}

async function init(){const base=normalizeData(await fetch('../data.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.json()));let saved=null;for(const k of [NEW_KEY,OLD_KEY]){try{saved=JSON.parse(localStorage.getItem(k)||'null');if(saved)break}catch{}}data=saved?normalizeData({...base,...saved}):base;render()}
function fileField(path,label,value){return `<label>${label}<span class="upload"><input type="file" accept="image/*" data-upload="${path}"></span>${value?`<img class="preview" src="${esc(value)}" alt="">`:''}</label>`}
function checkField(path,label,value){return `<label class="check"><input type="checkbox" data-check="${path}" ${value!==false?'checked':''}> ${label}</label>`}
function videoField(path,label,value){return `<div class="wide"><label>${label}<input data-path="${path}" value="${esc(value||'')}" placeholder="Link MP4/WebM hoặc YouTube"></label><label class="upload">Hoặc chọn video nhỏ<input type="file" accept="video/mp4,video/webm" data-video-upload="${path}"></label></div>`}

function treeEditor(path,items,depth=0){return `<div class="option-tree" data-tree-root="${esc(path)}">${(items||[]).map((o,i)=>treeNode(`${path}.${i}`,o,i,depth)).join('')||'<p class="section-note">Chưa có lựa chọn.</p>'}<button type="button" class="small-btn add" data-add-tree="${esc(path)}">+ Thêm lựa chọn</button></div>`}
function treeNode(path,o,i,depth){const childrenPath=path+'.children',hasDesc=o.hasDescription===true,hasChildren=o.hasChildren===true;return `<div class="tree-node"><div class="tree-head"><b>Lựa chọn ${i+1}${depth?` · cấp ${depth+1}`:''}</b><button type="button" class="small-btn danger" data-remove-tree="${esc(path)}">Xóa</button></div><div class="tree-mode-row"><label class="mini-check"><input type="checkbox" data-tree-toggle="${esc(path)}.hasDescription" ${hasDesc?'checked':''}> Có mô tả</label><label class="mini-check"><input type="checkbox" data-tree-toggle="${esc(path)}.hasChildren" ${hasChildren?'checked':''}> Có lựa chọn con</label></div><div class="tree-fields"><label>Tên<input data-path="${esc(path)}.label" value="${esc(o.label||'')}"></label>${hasChildren?'':`<label>Link đích<input data-path="${esc(path)}.url" value="${esc(o.url||'')}" placeholder="https://..."></label>`}${hasDesc?`<label class="full">Mô tả (không bắt buộc nội dung)<input data-path="${esc(path)}.description" value="${esc(o.description||'')}" placeholder="Ví dụ: Khuyên dùng, bản ổn định..."></label>`:''}</div>${hasChildren?`<div class="tree-actions"><button type="button" class="small-btn add" data-add-tree="${esc(childrenPath)}">+ Thêm lựa chọn con</button></div>${o.children?.length?`<div class="children">${o.children.map((c,j)=>treeNode(`${childrenPath}.${j}`,c,j,depth+1)).join('')}</div>`:'<p class="section-note child-note">Chưa có lựa chọn con.</p>'}`:''}</div>`}
function previewEditor(p,i){const imgs=p.previewImages||[];return `<div class="wide guide-box preview-admin"><div class="bar"><b>Ảnh Preview (${imgs.length})</b><label class="small-btn add multi-upload">+ Chọn nhiều ảnh<input type="file" accept="image/*" multiple data-preview-multi="${i}"></label></div><p class="section-note">Có thể chọn nhiều ảnh cùng lúc. Ảnh mới sẽ được thêm vào danh sách hiện tại.</p>${imgs.length?`<div class="preview-admin-grid">${imgs.map((src,j)=>`<div class="photo-tile"><img src="${esc(src)}" alt=""><div class="photo-actions"><label class="small-btn">Thay<input type="file" accept="image/*" data-preview-upload="${i}" data-preview-index="${j}"></label><button type="button" class="small-btn danger" data-remove-preview="${i}" data-preview-index="${j}">Xóa</button></div></div>`).join('')}</div>`:'<p class="section-note empty-preview">Chưa có ảnh Preview.</p>'}</div>`}
function guideFields(p,i){return `<div class="wide guide-box"><label>Kiểu hướng dẫn<select data-path="products.${i}.guideType" data-guide-type-index="${i}"><option value="text" ${p.guideType==='text'?'selected':''}>Nội dung chữ</option><option value="video" ${p.guideType==='video'?'selected':''}>Xem video</option><option value="link" ${p.guideType==='link'?'selected':''}>Mở đường link</option><option value="choices" ${p.guideType==='choices'?'selected':''}>Nhiều lựa chọn lồng nhau</option></select></label>${p.guideType==='text'?`<label>Nội dung hướng dẫn<textarea data-path="products.${i}.guideText">${esc(p.guideText||'')}</textarea></label>`:''}${p.guideType==='video'?videoField(`products.${i}.guideVideo`,'Video hướng dẫn',p.guideVideo):''}${p.guideType==='link'?`<label>Link hướng dẫn<input data-path="products.${i}.guideUrl" value="${esc(p.guideUrl||'')}" placeholder="https://..."></label>`:''}${p.guideType==='choices'?treeEditor(`products.${i}.guideOptions`,p.guideOptions||[]):''}</div>`}

function render(){
  const token=loadGithubToken();$('#githubFields').innerHTML=`<label class="wide token-row">GitHub Token<input type="password" data-gh="token" value="${esc(token)}" autocomplete="off" placeholder="github_pat_..."><button type="button" id="toggleToken">Hiện</button></label><p class="token-help">Repo cố định: <b>${GH_OWNER}/${GH_REPO}</b> · nhánh <b>${GH_BRANCH}</b> · file <b>${GH_PATH}</b>. Token cần quyền Contents: Read and write.</p>`;
  $('#mainFields').innerHTML=[['profileName','Tên hiển thị'],['helloText','Dòng nhỏ phía trên'],['subtitle','Dòng Gamer'],['avatar','Ảnh đại diện','file'],['bellIcon','Icon thông báo','file'],['footer','Chân trang'],['counterPrefix','Mã bộ đếm']].map(([k,l,t])=>t==='file'?fileField(k,l,data[k]):`<label>${l}<input data-path="${k}" value="${esc(data[k]||'')}"></label>`).join('');
  $('#effectFields').innerHTML=`<label class="wide">Link nhạc MP3 trực tiếp<input data-path="musicUrl" value="${esc(data.musicUrl||'')}"></label><label>Âm lượng<input type="number" min="0" max="1" step="0.05" data-path="musicVolume" value="${esc(data.musicVolume??.45)}"></label>${checkField('musicAutoplay','Tự phát nhạc',data.musicAutoplay)}${checkField('effects.particles','Hạt sáng bay',data.effects.particles)}${checkField('effects.avatarGlow','Hiệu ứng avatar',data.effects.avatarGlow)}${checkField('effects.verifiedShine','Hiệu ứng tích xanh',data.effects.verifiedShine)}${checkField('effects.backgroundMotion','Nền chuyển động',data.effects.backgroundMotion)}`;
  $('#noticeList').innerHTML=(data.notifications||[]).map((n,i)=>`<div class="item"><div class="item-head"><b>Thông báo ${i+1}</b><button class="remove" data-remove-notice="${i}">Xóa</button></div><div class="grid"><label>Tiêu đề<input data-path="notifications.${i}.title" value="${esc(n.title||'')}"></label><label>Nút/link hiển thị<input data-path="notifications.${i}.linkLabel" value="${esc(n.linkLabel||'Xem chi tiết')}"></label><label class="wide">Nội dung<textarea data-path="notifications.${i}.text">${esc(n.text||'')}</textarea></label><label class="wide">Link (không bắt buộc)<input data-path="notifications.${i}.link" value="${esc(n.link||'')}" placeholder="https://..."></label></div></div>`).join('');
  $('#socialList').innerHTML=(data.socials||[]).map((s,i)=>`<div class="item"><div class="item-head"><b>Icon ${i+1}</b><button class="remove" data-remove-social="${i}">Xóa</button></div><div class="grid">${fileField(`socials.${i}.image`,'Ảnh icon',s.image)}<label>Tên<input data-path="socials.${i}.name" value="${esc(s.name||'')}"></label><label class="wide">Đường dẫn<input data-path="socials.${i}.url" value="${esc(s.url||'')}"></label></div></div>`).join('');
  $('#productList').innerHTML=(data.products||[]).map((p,i)=>`<div class="item"><div class="item-head"><b>Sản phẩm ${i+1}</b><button class="remove" data-remove-product="${i}">Xóa</button></div><div class="grid"><label>Tiêu đề<input data-path="products.${i}.title" value="${esc(p.title||'')}"></label><label>Mô tả sản phẩm<input data-path="products.${i}.description" value="${esc(p.description||'')}"></label>${fileField(`products.${i}.cover`,'Ảnh menu',p.cover)}${fileField(`products.${i}.logo`,'Logo game',p.logo)}<label>Nhãn nền tảng<input data-path="products.${i}.platform" value="${esc(p.platform||'')}"></label><div class="wide action-config"><b>Nút Tải xuống</b><p class="section-note">Nếu không thêm lựa chọn bên dưới, nút sẽ mở link trực tiếp này.</p><label>Link trực tiếp<input data-path="products.${i}.downloadUrl" value="${esc(p.downloadUrl||'')}" placeholder="https://..."></label>${treeEditor(`products.${i}.downloadOptions`,p.downloadOptions)}</div><div class="wide action-config"><b>Nút Lấy key</b><p class="section-note">Nếu không thêm lựa chọn bên dưới, nút sẽ mở link trực tiếp này.</p><label>Link trực tiếp<input data-path="products.${i}.keyUrl" value="${esc(p.keyUrl||'')}" placeholder="https://..."></label>${treeEditor(`products.${i}.keyOptions`,p.keyOptions)}</div>${previewEditor(p,i)}${guideFields(p,i)}</div></div>`).join('')
}

function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.84))};img.onerror=reject;img.src=r.result};r.readAsDataURL(file)})}
function readVideo(file){return new Promise((resolve,reject)=>{if(file.size>8*1024*1024)return reject(new Error('Video quá lớn. Hãy dùng link video.'));const r=new FileReader();r.onerror=reject;r.onload=()=>resolve(r.result);r.readAsDataURL(file)})}

document.addEventListener('input',e=>{if(e.target.dataset.path){let v=e.target.value;if(e.target.type==='number')v=Number(v);setPath(e.target.dataset.path,v)}if(e.target.dataset.check)setPath(e.target.dataset.check,e.target.checked)});
document.addEventListener('change',async e=>{
  if(e.target.dataset.treeToggle){setPath(e.target.dataset.treeToggle,e.target.checked);render();return}
  if(e.target.dataset.guideTypeIndex!==undefined){setPath(e.target.dataset.path,e.target.value);render();return}
  if(e.target.dataset.upload&&e.target.files[0]){try{setPath(e.target.dataset.upload,await compress(e.target.files[0]));render()}catch{alert('Không đọc được ảnh.')}}
  if(e.target.dataset.previewMulti!==undefined&&e.target.files?.length){const idx=+e.target.dataset.previewMulti;try{const files=[...e.target.files],converted=[];for(const file of files)converted.push(await compress(file));data.products[idx].previewImages.push(...converted);render()}catch{alert('Không đọc được một hoặc nhiều ảnh.')}}
  if(e.target.dataset.previewUpload!==undefined&&e.target.files[0]){try{data.products[+e.target.dataset.previewUpload].previewImages[+e.target.dataset.previewIndex]=await compress(e.target.files[0]);render()}catch{alert('Không đọc được ảnh.')}}
  if(e.target.dataset.videoUpload&&e.target.files[0]){try{setPath(e.target.dataset.videoUpload,await readVideo(e.target.files[0]));render()}catch(err){alert(err.message)}}
});

document.addEventListener('click',e=>{
  const t=e.target;
  if(t.dataset.removeNotice!==undefined){data.notifications.splice(+t.dataset.removeNotice,1);render()}
  if(t.dataset.removeSocial!==undefined){data.socials.splice(+t.dataset.removeSocial,1);render()}
  if(t.dataset.removeProduct!==undefined){data.products.splice(+t.dataset.removeProduct,1);render()}
  if(t.dataset.addPreview!==undefined){data.products[+t.dataset.addPreview].previewImages.push('');render()}
  if(t.dataset.removePreview!==undefined){data.products[+t.dataset.removePreview].previewImages.splice(+t.dataset.previewIndex,1);render()}
  if(t.dataset.addTree){const a=arrayAt(t.dataset.addTree);if(a){a.push({label:`Lựa chọn ${a.length+1}`,description:'',hasDescription:false,url:'',hasChildren:false,children:[]});render()}}
  if(t.dataset.removeTree){const parts=t.dataset.removeTree.split('.'),idx=Number(parts.pop()),parent=arrayAt(parts.join('.'));if(parent){parent.splice(idx,1);render()}}
});
$('#addNotice').onclick=()=>{data.notifications.push({title:'Thông báo mới',text:'',link:'',linkLabel:'Xem chi tiết'});render()};
$('#addSocial').onclick=()=>{data.socials.push({image:'assets/telegram.svg',url:'#',name:'Liên kết'});render()};
$('#addProduct').onclick=()=>{data.products.push(normalizeProduct({title:'SẢN PHẨM MỚI',description:'Cập nhật hôm nay',cover:'assets/cover1.svg',logo:'assets/logo.svg',platform:'iOS',downloadUrl:'',keyUrl:'',previewImages:[],downloadOptions:[],keyOptions:[],guideType:'text',guideText:'',guideOptions:[]}));render()};
$('#saveBtn').onclick=()=>{localStorage.setItem(NEW_KEY,JSON.stringify(data));localStorage.removeItem(OLD_KEY);alert('Đã lưu để xem thử trên thiết bị này.');location.href='../'};
$('#resetBtn').onclick=()=>{localStorage.removeItem(NEW_KEY);localStorage.removeItem(OLD_KEY);location.reload()};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};

document.addEventListener('click',async e=>{
  if(e.target.id==='toggleToken'){const i=document.querySelector('[data-gh="token"]');i.type=i.type==='password'?'text':'password';e.target.textContent=i.type==='password'?'Hiện':'Ẩn'}
  if(e.target.id==='testGithubBtn'){try{setGithubStatus('Đang kiểm tra...');const s=githubSettings();if(!s.token)throw new Error('Hãy nhập GitHub Token.');saveGithubToken(s.token);await githubRequest(`https://api.github.com/repos/${encodeURIComponent(s.owner)}/${encodeURIComponent(s.repo)}`,s.token);setGithubStatus('Kết nối GitHub thành công.','ok')}catch(err){setGithubStatus(err.message,'err')}}
  if(e.target.id==='githubSaveBtn'){const b=e.target;try{b.disabled=true;setGithubStatus('Đang cập nhật data.json...');localStorage.setItem(NEW_KEY,JSON.stringify(data));localStorage.removeItem(OLD_KEY);await saveDataToGithub();setGithubStatus('Đã lưu lên GitHub cho tất cả thiết bị.','ok')}catch(err){setGithubStatus(err.message,'err')}finally{b.disabled=false}}
});
